- Controller/Adminhtml/Import/Ajax.php
- Helper/Data.php
- Observer/Config.php
- view/adminhtml/web/js/import.js
Sends start and end activities for the import 🏁 
===
Jira story [#MET-2029](https://metrilojira.atlassian.net/browse/MET-2029) in project *Features team*:
> MET-2029: Magento 2 import activities

- Helper/Data.php
- Model/Analytics.php
- Observer/AddToCart.php
- development/docker-compose.yml
- development/installation
➕ Adds SKU data with `view_product`, `add_to_cart` and `order` events
🔧 Fixes the development installation script
===
Jira story [#MET-2033](https://metrilojira.atlassian.net/browse/MET-2033) in project *Features team*:
> MET-2033: Magento 2 sku numbers

- Block/Analytics.php
- Block/System/Config/Button/Import.php
- Controller/Adminhtml/Import/Ajax.php
- Helper/AdminStoreResolver.php
- Helper/Data.php
- Model/Import.php
- Observer/Config.php
- Observer/Order.php
🔧 Fixes store resolving in admin functionalities
🖊 Logs errors in `metrilo.log`
> MET-2081: [Magento 2] Multistore issues

- Helper/ImagePathResolver.php
- Helper/OrderSerializer.php
- Model/Analytics.php
Implemented new image helper in order to access product image base path (first image from product media gallery) and get a timestamp of last modification attached to the url.
> Plg 27/bigger product images

- Controller/Adminhtml/Import/Ajax.php
- Model/Customer.php
- Model/CustomerData.php
Changes include new class for importing Customer data to Metrilo. The class will output all customers data in the described structure. Output can be accessed from the admin module config page when the import button is clicked and will be displayed in browser developer window on Network section Preview scope in json format.
===
Jira story [#PLG-36](https://metrilojira.atlassian.net/browse/PLG-36) in project *Plugins*:
> The import button should do the following:
> * Generate an array containing all customer properties according to V2 tracking format (see bellow)
> * Use the shared library to send the data to the new tracking
> 
> The subscribed status is taken from the "Subscribed to newsletter" field of the customer
> 
> {noformat}
> "email": "johnybravo@metrilo.com",
> "createdAt": …
> PLG-36: [Import] Customers

- Controller/Adminhtml/Import/Ajax.php
- Model/ProductData.php
Changes include new class for importing Product data to Metrilo. The class will output all products data in the described structure. Output can be accessed from the admin module config page when the import button is clicked and will be displayed in browser developer window on Network section Preview scope in json format.
===
Jira story [#PLG-39](https://metrilojira.atlassian.net/browse/PLG-39) in project *Plugins*:
> The import button should do the following:
> * Generate an array containing all products properties according to V2 tracking format (see bellow)
> * Use the shared library to send the data to the new tracking
> 
> {noformat}
> "categories": [
>   {
>     "id": 12
>   }
> ],
> "id": 91,
> "sku": "CM01-R",
> "imageUrl": …
> PLG-39: [Import] Products

- view/adminhtml/web/js/import.js
The js text is subject of discussion, but it is taken from the working model of m1 and woo modules.
> PLG-43: import on empty store (without orders)

- composer.json
- etc/module.xml
New module version that is excluding extra product variations from metrilo api call.
> version bump 1.1.5

- Api/Client.php
- Api/Connection.php
- Api/Validator.php
- Controller/Adminhtml/Import/Ajax.php
- Helper/Data.php
- Model/CategoryData.php
- Model/CustomerData.php
- Model/Import.php
- Model/OrderData.php
- Model/ProductData.php
- etc/adminhtml/system.xml
- view/adminhtml/templates/system/config/button/import.phtml
- view/adminhtml/web/js/import.js
Initial commit of new AJAX import logic.
> PLG-64 Pagination for all resources during m2 import

- Block/System/Config/Button/Import.php
- Controller/Adminhtml/Import/Ajax.php
- Helper/ApiClient.php
- Helper/Data.php
- Helper/OrderSerializer.php
- Model/Import.php
- Model/OrderData.php
- Observer/Order.php
- view/adminhtml/templates/system/config/button/import.phtml
> PLG-77: Track order changes

- composer.json
- etc/module.xml
New module version is required to update the module technical compatibility for magento system up to version 2.3.1
> version bump 1.1.6

- Block/Analytics.php
- Model/Events/PageViewEvent.php
- Model/Events/ProductViewEvent.php
- etc/di.xml
- view/frontend/templates/page/analytics.phtml
New class providing necessary data for tracking page views.
> PLG-111: Track Page View Event

- Block/Analytics.php
- Model/Events/CategoryView.php
- Model/Events/CategoryViewEvent.php
- Model/Events/PageView.php
- Model/Events/ProductView.php
- etc/di.xml
New class responsible for tracking of category view front-end events.
> Plg-113/track category view event

- Block/Analytics.php
- Model/Events/CartView.php
New event responsible for cart view action tracking.
> PLG-115: Track Cart View Event

- Block/Analytics.php
- Model/Events/CheckoutView.php
- etc/di.xml
Simple class responsible for tracking checkout start process.
> PLG-121: Track checkout event

- Helper/CustomerSerializer.php
Apply customer group as tags param during customer events.
> PLG-18: Magento User Groups Sync

- Observer/AddToCart.php
- Observer/RemoveFromCart.php
Simple conditional for module availability check.
> PLG-123: Check Module Status In Cart Observers

- Controller/Adminhtml/Import/Ajax.php
Special events for start/end of the manual back-end import.
> PLG-68: Added import_start and import_end special events

- composer.json
- etc/module.xml
New module version patching the error outputs when category/product page is loaded without registry object.
> version bump 1.1.7

- Api/Client.php
- Api/Validator.php
- Helper/ApiClient.php
Extract system log location and pass it as param to client class instead of using hardcoded path in the Validator class.
> PLG-129: Log Path for Library Validator class

- CustomerData/PrivateData.php
- etc/frontend/di.xml
- etc/frontend/sections.xml
- view/frontend/templates/page/analytics.phtml
- view/frontend/web/js/private-data.js
Customer specific events add/remove from cart and identify can now be send when full page cache is enabled.
> PLG-119: FPC hole punching

- Api/Validator.php
- Controller/Adminhtml/Import/Ajax.php
- Helper/DeletedProductSerializer.php
- Model/DeletedProductData.php
- Model/OrderData.php
- view/adminhtml/web/js/import.js
New functionality for filtering the deleted products from orders and syncing them with Metrilo.
> PLG-140: Import Deleted Products

- Helper/CustomerSerializer.php
- Helper/MetriloCustomer.php
- Observer/Customer.php
- etc/events.xml
Added customer event for order creation during guest checkout and code refactoring for the customer observer class
> KYP-672: Send customer event during guest checkout.

- Model/Events/AddToCart.php
- Model/Events/RemoveFromCart.php
Updated cart events to track the selected product options instead of parent product
> KYP-729: Add_to/Remove_from cart events update

- Helper/DeletedProductSerializer.php
- Helper/OrderSerializer.php
- Helper/ProductOptions.php
- Model/Events/AddToCart.php
- Model/Events/RemoveFromCart.php
For legacy reasons m1 projects are sending product option sku instead of id, this modification should handle the migration from m1 to m2 module.
> KYP-762: Added fallback for option ID if SKU is not present

- Helper/OrderSerializer.php
- Observer/AddToCart.php
- Observer/RemoveFromCart.php
Fallback logic to track product option ID if same product SKU is not available.
> KYP-761: Track product option ID if SKU is not present

- Helper/ProductOptions.php
- Helper/ProductSerializer.php
- Model/ProductData.php
Simple modification that can detect if a product have special price configuration.
> KYP-774: Track product special price data

- Observer/Customer.php
Simple modification that will allow the capture of guest customers subscribing to newsletter.
> KYP-827: magento2 default newsletter subscribe form handle

- Model/ProductData.php
- Test/Unit/Model/ProductDataTest.php
Unit test and refactoring for Product model.
> KYP-720: Product model test and refactoring

- Model/OrderData.php
- Test/Unit/Model/OrderDataTest.php
Unit test and refactoring for Order model.
> KYP-720: Order model test

- Test/Unit/Model/DeletedProductDataTest.php
Unit test for Deleted product model.
> KYP-720: Deleted product model test

- Model/CategoryData.php
- Test/Unit/Model/CategoryDataTest.php
Unit test and refactoring for Category model.
> KYP-720: Category model test and refactoring

- Model/CustomerData.php
- Test/Unit/Model/CustomerDataTest.php
Unit test and refactoring for Customer model.
> KYP-720: Customer model test and refactoring

- Test/Unit/Model/Events/AddToCartTest.php
- Test/Unit/Model/Events/CartViewTest.php
- Test/Unit/Model/Events/CatalogSearchTest.php
- Test/Unit/Model/Events/CategoryViewTest.php
- Test/Unit/Model/Events/CheckoutViewTest.php
- Test/Unit/Model/Events/IdentifyCustomerTest.php
- Test/Unit/Model/Events/PageViewTest.php
- Test/Unit/Model/Events/ProductViewTest.php
- Test/Unit/Model/Events/RemoveFromCartTest.php
Unit tests for front-end event models.
> KYP-720: Front-end event models tests

- Test/Unit/Observer/AddToCartTest.php
- Test/Unit/Observer/CategoryTest.php
- Test/Unit/Observer/ConfigTest.php
- Test/Unit/Observer/CustomerTest.php
- Test/Unit/Observer/IdentifyCustomerTest.php
- Test/Unit/Observer/OrderTest.php
- Test/Unit/Observer/ProductTest.php
- Test/Unit/Observer/RemoveFromCartTest.php
Unit tests for Observer classes.
> KYP-720: Observer tests

- Helper/DeletedProductSerializer.php
- Test/Unit/Helper/CategorySerializerTest.php
- Test/Unit/Helper/CustomerSerializerTest.php
- Test/Unit/Helper/DeletedProductSerializerTest.php
- Test/Unit/Helper/OrderSerializerTest.php
- Test/Unit/Helper/ProductSerializerTest.php
Unit tests and refactoring for serialize Helper classes.
> KYP-720: Serializer helpers tests and refactoring

- Controller/Adminhtml/Import/Ajax.php
- Test/Unit/Controller/AjaxTest.php
- Test/Unit/CustomerData/PrivateDataTest.php
Unit tests and refactoring for FPC private data and  Controller classes.
> KYP-720: FPC private data and controller tests plus refactoring
